/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PengingatObat;

import java.util.ArrayList;

/**
 *
 * @author WINDOWS 11
 */
public class formObat extends javax.swing.JFrame {

    private ArrayList<Obat> daftarObat = new ArrayList<>();

    /**
     * Creates new form formObat
     */
    public formObat() {
        initComponents();
        dokterField.setEnabled(false); // Nonaktifkan input nama dokter secara default
        resepField.setEnabled(false); // Nonaktifkan input nomor resep secara default
        kategoriField.setEnabled(false); // Nonaktifkan input kategori obat secara default
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jumlahField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jadwalField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resepButton = new javax.swing.JRadioButton();
        bebasButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        dokterField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        resepField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kategoriField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("PENGINGAT OBAT");

        jLabel2.setText("Jumlah Obat : ");

        jLabel3.setText("Nama Obat : ");

        jLabel4.setText("Jadwal Obat : ");

        jadwalField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jadwalFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Obat");

        resepButton.setText("Resep");
        resepButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resepButtonActionPerformed(evt);
            }
        });

        bebasButton.setText("Bebas");
        bebasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebasButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Nama Dokter : ");

        dokterField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("No Resep : ");

        jLabel8.setText("Kategori Obat :");

        kategoriField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriFieldActionPerformed(evt);
            }
        });

        addButton.setText("Tambahkan");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        displayArea.setColumns(20);
        displayArea.setRows(5);
        jScrollPane1.setViewportView(displayArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(23, 23, 23)
                            .addComponent(resepField))
                        .addComponent(jLabel5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(9, 9, 9)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jadwalField, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                                    .addComponent(namaField)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(3, 3, 3)
                                .addComponent(dokterField, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resepButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bebasButton))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(kategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jadwalField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resepButton)
                    .addComponent(bebasButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dokterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(resepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kategoriField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Fungsi untuk menangani jenis obat yang dipilih
    private void handleObatTypeSelection() {
        if (resepButton.isSelected()) {
            dokterField.setVisible(true); // Tampilkan nama dokter
            resepField.setVisible(true);  // Tampilkan nomor resep
            kategoriField.setVisible(false); // Sembunyikan kategori obat
        } else if (bebasButton.isSelected()) {
            kategoriField.setVisible(true); // Tampilkan kategori obat
            dokterField.setVisible(false); // Sembunyikan nama dokter
            resepField.setVisible(false);  // Sembunyikan nomor resep
        }
    }

    private void jadwalFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jadwalFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jadwalFieldActionPerformed

    private void resepButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepButtonActionPerformed
        // TODO add your handling code here:
        // Saat Resep dipilih, aktifkan form terkait resep
        dokterField.setEnabled(true);
        resepField.setEnabled(true);
        kategoriField.setEnabled(false);

        // Pastikan hanya Resep yang aktif, Bebas dinonaktifkan
        bebasButton.setSelected(false);
    }//GEN-LAST:event_resepButtonActionPerformed

    private void kategoriFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriFieldActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String jumlah = jumlahField.getText();
        String nama = namaField.getText();
        String jadwal = jadwalField.getText();

        if (resepButton.isSelected()) {
            // Obat Resep
            String dokter = dokterField.getText();
            String resep = resepField.getText();
            
            daftarObat.add(new ObatResep(nama, jadwal, dokter, resep, jumlah)); // Menambahkan obat resep
        } else if (bebasButton.isSelected()) {
            // Obat Bebas
            String kategori = kategoriField.getText();
            daftarObat.add(new ObatBebas(nama, jadwal, kategori, jumlah)); // Menambahkan obat bebas
        }

        // Menampilkan daftar obat yang telah ditambahkan
        tampilkanDaftarObat();

        // Mengosongkan field setelah menambah obat
        jumlahField.setText("");
        namaField.setText("");
        jadwalField.setText("");
        dokterField.setText("");
        resepField.setText("");
        kategoriField.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void dokterFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dokterFieldActionPerformed

    private void bebasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebasButtonActionPerformed
        // Saat Bebas dipilih, aktifkan form terkait kategori obat
        kategoriField.setEnabled(true);
        dokterField.setEnabled(false);
        resepField.setEnabled(false);

        // Pastikan hanya Bebas yang aktif, Resep dinonaktifkan
        resepButton.setSelected(false);
    }//GEN-LAST:event_bebasButtonActionPerformed

    // Fungsi untuk menampilkan daftar obat pada text area
    private void tampilkanDaftarObat() {
        displayArea.setText(""); // Kosongkan area display
        for (Obat obat : daftarObat) {
            displayArea.append(obat.toString() + "\n"); // Menampilkan daftar obat
        }
    }

    // Kelas abstrak Obat
    public abstract class Obat {

        protected String nama;
        protected String jadwal;
        protected String jumlah;

        public Obat(String nama, String jadwal, String jumlah) {
            this.nama = nama;
            this.jadwal = jadwal;
            this.jumlah = jumlah;
        }

        @Override
        public abstract String toString();
    }

    // Kelas untuk Obat Resep
    public class ObatResep extends Obat {

        private String dokter;
        private String resep;

        public ObatResep(String nama, String jadwal, String dokter, String resep, String jumlah) {
            super(nama, jadwal, jumlah);
            this.dokter = dokter;
            this.resep = resep;
        }

        @Override
        public String toString() {
            return "Jumlah Obat : " + jumlah + "\n" 
                    + "Nama Obat : " + nama + "\n" 
                    + "Jadwal : " + jadwal + "\n" 
                    + "Dokter : " + dokter + "\n" 
                    + "No Resep : " + resep + "\n"
                    + "=========================";
        }
    }

    // Kelas untuk Obat Bebas
    public class ObatBebas extends Obat {

        private String kategori;

        public ObatBebas(String nama, String jadwal, String kategori, String jumlah) {
            super(nama, jadwal, jumlah);
            this.kategori = kategori;
        }

        @Override
        public String toString() {
            return "Jumlah Obat : " + jumlah + "\n" 
                    + "Nama Obat : " + nama + "\n" 
                    + "Jadwal : " + jadwal + "\n" 
                    + "Kategori : " + kategori + "\n"
                    + "=========================";
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formObat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formObat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton bebasButton;
    private javax.swing.JTextArea displayArea;
    private javax.swing.JTextField dokterField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jadwalField;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JTextField kategoriField;
    private javax.swing.JTextField namaField;
    private javax.swing.JRadioButton resepButton;
    private javax.swing.JTextField resepField;
    // End of variables declaration//GEN-END:variables
}
